language: node_js

node_js:
  - "8.11.1"

sudo: required

os:
  - linux
  - osx

env:
  - TARGET_ARCH=x64

services:
  - docker

osx_image: xcode9.0

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - xvfb
      - libusb-1.0-0
      - libusb-1.0-0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -it -d -p 3001:3001 hunterlong/btcregtest-insight:latest; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -it -d -p 3005:3005 hunterlong/ltcregtest-insight:latest; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /bin/bash -c ./.travis/travis-test.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /bin/bash -c ./.travis/release-osx.sh; fi